import type { Metadata } from "next";
import {  Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
	metadataBase: new URL("https://localhost:3000"),

	title: "Prashant",
	authors: {
		name: "Prashant",
	},

	description:
		"In this page i detail all of my filed and i describe my work and all as engineering in our web app",
	openGraph: {
		title: "Prashant",
		description:
			"Hello my name is Prashant Singh and I m  Software engineering. devloping website applications. My journey so far has included working with both front-end and back-end development.",
		url: "https://localhost:3000",
		siteName: "Prashant",
		images: "/og.png",
		type: "website",
	},
	keywords: ["daily web coding", "chensokheng", "dailywebcoding"],
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={spaceGrotesk.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
